apiVersion: apps/v1
kind: Deployment
metadata:
 name: nmdevops-deployment # name of the deployment
 
spec:
 template: # pod defintion
   metadata:
     name: nmdevops # name of the pod
     labels:
       app: nmdevops
       tier: frontend
   spec:
     containers:
       - name: nmdevops
         image: easweralu/nmdevops:latest
 replicas: 3
 selector: # Mandatory, Select the pods which needs to be in the replicaset
   matchLabels:
     app: nmdevops
     tier: frontend
